import GlobalState from "../context/index";
import "../styles/globals.css";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalState>
          <div className="flex h-screen overflow-hidden">
            <Sidebar />

            <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
              <Header />

              <main>
                <div className="mx-auto max-w-2xl p-4 md:p-6 2xl:p-10">
                  {children}
                </div>
              </main>
            </div>
          </div>
        </GlobalState>
      </body>
    </html>
  );
}
